name: Build & Deploy Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      -      - name: Build site
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p _site

          if [[ -f "data/Normativas_Beneficios_Assistenciais_CGRAN.xlsx" ]]; then
            echo ">> Planilha encontrada. Ingerindo e publicando..."
            python -m bpa.cli ingest data/Normativas_Beneficios_Assistenciais_CGRAN.xlsx --out-json data/norms.json
            echo ">> Conteudo de data/ apos ingest:"
            ls -la data || true

            echo ">> Executando publish..."
            python -m bpa.cli publish --out _site --sqlite _site/bpc_normativos.sqlite

            echo ">> Forcando build_site (garantia de index.html)..."
            python - <<'PY'
from bpa.publish.emit_site import build_site
build_site("data/norms.json","_site")
print("OK forced build_site")
PY
          else
            echo ">> Planilha NAO encontrada. Publicando placeholder..."
            printf '<!doctype html><meta charset="utf-8"><title>banco-normativos-ba</title><h1>Banco de Normativos de Beneficios Assistenciais</h1><p>Adicione sua planilha em <code>data/Normativas_Beneficios_Assistenciais_CGRAN.xlsx</code> e faca novo push.</p>' > _site/index.html
          fi

          echo ">> Conteudo de _site apos publish/force:"
          ls -la _site || true

          # Fallback final (se algo muito errado acontecer)
          if [[ ! -f "_site/index.html" ]]; then
            echo ">> Nenhum index.html encontrado; criando fallback final."
            printf '<!doctype html><meta charset="utf-8"><title>banco-normativos-ba</title><h1>Site gerado</h1><p>Sem index; verifique o passo publish.</p>' > _site/index.html
          fi

          : > _site/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
